### PR TITLE
chore: get_prime_numbers docstring

### PR DESCRIPTION
**Pull request by theNamskov**
I added a description of the problem and the solution to aid in understanding.

### CODE REVIEW

**Review by OliverMensahDev — COMMENTED** [review]
I'm not convinced with the `o(n)` Time complexity.
Take a close look at this.


```
for(long long i=2; i<boundary; ++i) if(ar[i]) {
        long long j=i*2;
        while(j<boundary){
            ar[j] = false;
            j+=i;
        }
        counter++;
        prime_numbers.push(i);
    }

```

**Comment by theNamskov** [comment]
> I'm not convinced with the `o(n)` Time complexity.
> Take a close look at this.
> 
> ```
> for(long long i=2; i<boundary; ++i) if(ar[i]) {
>         long long j=i*2;
>         while(j<boundary){
>             ar[j] = false;
>             j+=i;
>         }
>         counter++;
>         prime_numbers.push(i);
>     }
> ```

Me kraaa it looks like I'm not, but this is where I looked at it from.
Given that we know that the prime number we are starting with is `2`, we'll, at worst case, go through half of the elements in the array(that is, inside the `while` loop)
And for the outer loop, since it's dependent on those that are actually prime numbers, for a given set of elements in an array we can say that the number of prime integers will always be at most half.
So if we have from 1-20, the number of primes are 7 (`[2, 3, 5, 7, 11, 13, 17]`). It's only these that are going to execute the `while` loop, with `2` doing the most work in there, in that it'll go through half the number of elements in the array. It'll not be so for the others.
For the outer loop we are sure of an `O(n)` because all elements will make the `if` check.


Looking at what I've said now, I think it'll be an `O(nlogn)`😅

**Comment by OliverMensahDev** [comment]
> > I'm not convinced with the `o(n)` Time complexity.
> > Take a close look at this.
> > ```
> > for(long long i=2; i<boundary; ++i) if(ar[i]) {
> >         long long j=i*2;
> >         while(j<boundary){
> >             ar[j] = false;
> >             j+=i;
> >         }
> >         counter++;
> >         prime_numbers.push(i);
> >     }
> > ```
> 
> Me kraaa it looks like I'm not, but this is where I looked at it from.
> Given that we know that the prime number we are starting with is `2`, we'll, at worst case, go through half of the elements in the array(that is, inside the `while` loop)
> And for the outer loop, since it's dependent on those that are actually prime numbers, for a given set of elements in an array we can say that the number of prime integers will always be at most half.
> So if we have from 1-20, the number of primes are 7 (`[2, 3, 5, 7, 11, 13, 17]`). It's only these that are going to execute the `while` loop, with `2` doing the most work in there, in that it'll go through half the number of elements in the array. It'll not be so for the others.
> For the outer loop we are sure of an `O(n)` because all elements will make the `if` check.
> 
> Looking at what I've said now, I think it'll be an `O(nlogn)`

Okay, but at what point does this code break down the input represent (n/2) to get `logn`.

**Comment by theNamskov** [comment]
In the while loop. For a given set of elements, the worst iteration will be n/2 because 2 is the least prime number. For every other prime number z, the iteration takes an n/z

**Comment by OliverMensahDev** [comment]
> In the while loop. For a given set of elements, the worst iteration will be n/2 because 2 is the least prime number. For every other prime number z, the iteration takes an n/z

can you share a file illustrating the breakdown because I don't seem to get it? Sample of such breakdown. 

https://en.wikipedia.org/wiki/File:Binary_search_complexity.svg 

https://en.wikipedia.org/wiki/File:Approximate-binary-search.svg

**Comment by theNamskov** [comment]
**n** = `[1, 2, 3, 4, 5, ..., 20]`

**Knowns:** **2** is the first prime number. We start from there

**First - `for` loop:** Every element makes an `if` check, which is a complexity of **1** for each, hence a value of **n**.

**Second - `while` loop:** Executes if the `if` truth factor resolves to `true`. 
- The number **2**(Our first prime is initially `true` so it evaluates and takes out **4, 6, 8, ..., 20**) takes out **_n/2_** of the elements out). This gives us a `logn` operation for **2**. This `while` loop only executes for a few numbers that are checked as `true` from the `while` loop. The number **2** has already taken half of them, so we are left with half to deal with. 
- The next number to evaluate is **3**, which will also in its own right take out **_n/3_** elements(`logn` operation). 
- The next one is **5**, since **4** got cancelled by **2**. **5** also takes out **_n/5_** elements(`logn`). 
- **6** gets cancelled by **2** (and **3**) and then we move to **7**, which also takes out **_n/7_** elements(`logn`). 
- Same for **11, 13, 17** and **19** since they are the only ones valid enough to cause the `while` loop to execute.

_Also, as we go up the numeric scale we see that the gap between the prime numbers increase, hence the `while` loop executes less frequently._

**Comment by OliverMensahDev** [comment]
> **n** = `[1, 2, 3, 4, 5, ..., 20]`
> 
> **Knowns:** **2** is the first prime number. We start from there
> 
> **First - `for` loop:** Every element makes an `if` check, which is a complexity of **1** for each, hence a value of **n**.
> 
> **Second - `while` loop:** Executes if the `if` truth factor resolves to `true`.
> 
> * The number **2**(Our first prime is initially `true` so it evaluates and takes out **4, 6, 8, ..., 20**) takes out **_n/2_** of the elements out). This gives us a `logn` operation for **2**. This `while` loop only executes for a few numbers that are checked as `true` from the `while` loop. The number **2** has already taken half of them, so we are left with half to deal with.
> * The next number to evaluate is **3**, which will also in its own right take out **_n/3_** elements(`logn` operation).
> * The next one is **5**, since **4** got cancelled by **2**. **5** also takes out **_n/5_** elements(`logn`).
> * **6** gets cancelled by **2** (and **3**) and then we move to **7**, which also takes out **_n/7_** elements(`logn`).
> * Same for **11, 13, 17** and **19** since they are the only ones valid enough to cause the `while` loop to execute.
> 
> _Also, as we go up the numeric scale we see that the gap between the prime numbers increase, hence the `while` loop executes less frequently._

Yeah but that does not throw half of the input away. It just makes less so it fits for a worst-case of n operations

**Comment by theNamskov** [comment]
Though the other inputs don't get thrown away, they don't go through the `while` loop process, essentially. They only attract a complexity of 1

**Comment by theNamskov** [comment]
Screenshot from 2020-08-21 07-33-34

**Comment by OliverMensahDev** [comment]
Thanks for the great input to this

**Pull request merged**
